version: 2.1

executors:
  build-agent:
    docker:
      - image: cimg/node:lts
    working_directory: /tmp/eslint-config

jobs:

  publish-beta:
    executor: build-agent
    steps:
      - checkout
      - run: npm run build
      - run: printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" > .npmrc
      - run: npm whoami
      - run: npm publish --access public beta

  publish-latest:
    executor: build-agent
    steps:
      - checkout
      - run: npm run build
      - run: printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" > .npmrc
      - run: npm whoami
      - run: npm publish --access public

workflows:
  development:
    jobs:
      - publish-beta:
          context: npm_publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+-.+$/
      - publish-latest:
          context: npm_publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
